version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    target-branch: master

  - package-ecosystem: gradle
    directory: /app/android
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    target-branch: master

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    target-branch: master
