name: ew_http
description: Ew Http Dart package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  http: ^1.1.2
  meta: ^1.15.0

dev_dependencies:
  mocktail: ^1.0.1
  test: ^1.24.9
  very_good_analysis: ^5.1.0
