name: ew_test_keys
description: An Encointer package to have common test keys.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dev_dependencies:
  test: ^1.24.9
  very_good_analysis: ^5.1.0
