name: ew_test_keys
description: An Encointer package to have common test keys.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1




  