name: ew_encointer_utils
description: Encointer Utils Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dev_dependencies:
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
